name: Auto Update Dashboard

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Cập nhật mỗi ngày lúc 7h sáng VN (tăng só kiểu 0 1 là 8h sáng theo UTF)
  workflow_dispatch:

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Thiết lập Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Cài đặt thư viện
        run: pip install requests matplotlib

      - name: Chạy script cập nhật
        run: python update_readme.py

      - name: Commit & Push
        run: |
          git config user.name "LONGDKZdev"
          git config user.email "longvh2549@gmail.com"
          git add .
          git commit -m "Auto update dashboard" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/LONGDKZdev/LONGDKZdev.git HEAD:main